package de.darthkali.kmm_bike_share.mockFactory

data class Countries(
    val countryList: List<String> = listOf(
        "Algeria",
        "Angola",
        "Egypt",
        "Bangladesh",
        "Niger",
        "Liechtenstein",
        "Namibia",
        "Bulgaria",
        "Bolivia",
        "Ghana",
        "Cocos (Keeling) Islands",
        "Pakistan",
        "Cape Verde",
        "Jordan",
        "Liberia",
        "Libya",
        "Malaysia",
        "British Indian Ocean Territory",
        "Puerto Rico",
        "Mayotte",
        "North Korea",
        "Tanzania",
        "Botswana",
        "Cambodia",
        "Trinidad and Tobago",
        "Paraguay",
        "Hong Kong",
        "Saudi Arabia",
        "Lebanon",
        "Slovenia",
        "Burkina Faso",
        "Slovakia",
        "Mauritania",
        "Croatia",
        "Chile",
        "China",
        "Saint Kitts and Nevis",
        "Jamaica",
        "San Marino",
        "Gibraltar",
        "Djibouti",
        "Guinea",
        "Finland",
        "Uruguay",
        "Thailand",
        "São Tomé and Príncipe",
        "Seychelles",
        "Nepal",
        "Christmas Island",
        "Laos",
        "Yemen",
        "Bouvet Island",
        "South Africa",
        "Kiribati",
        "Philippines",
        "Sint Maarten",
        "Romania",
        "Syria",
        "Macau",
        "Nicaragua",
        "Malta",
        "Kazakhstan",
        "Turks and Caicos Islands",
        "French Polynesia",
        "Niue",
        "Dominica",
        "United Kingdom",
        "Benin",
        "French Guiana",
        "Belgium",
        "Montserrat",
        "Togo",
        "Germany",
        "Guam",
        "Sri Lanka",
        "South Sudan",
        "Falkland Islands",
        "Pitcairn Islands",
        "Bonaire",
        "Guyana",
        "Costa Rica",
        "Cook Islands",
        "Morocco",
        "Northern Mariana Islands",
        "Comoros",
        "Hungary",
        "Turkmenistan",
        "Suriname",
        "Netherlands",
        "Bermuda",
        "Heard Island and McDonald Islands",
        "Chad",
        "Georgia",
        "Montenegro",
        "Mongolia",
        "Marshall Islands",
        "Martinique",
        "Belize",
        "Norfolk Island",
        "Myanmar",
        "Afghanistan",
        "Burundi",
        "British Virgin Islands",
        "Belarus",
        "Saint Barthélemy",
        "Grenada",
        "Tokelau",
        "Greece",
        "Lesotho",
        "Greenland",
        "Saint Helena",
        "Andorra",
        "Mozambique",
        "Tajikistan",
        "Haiti",
        "Mexico",
        "Zimbabwe",
        "Saint Lucia",
        "India",
        "Latvia",
        "Bhutan",
        "Saint Vincent and the Grenadines",
        "Vietnam",
        "Norway",
        "Czech Republic",
        "French Southern and Antarctic Lands",
        "Antigua and Barbuda",
        "Fiji",
        "Honduras",
        "Mauritius",
        "Dominican Republic",
        "Luxembourg",
        "Israel",
        "Federated States of Micronesia",
        "Peru",
        "Réunion",
        "Indonesia",
        "Vanuatu",
        "Republic of Macedonia",
        "Democratic Republic of the Congo",
        "Republic of the Congo",
        "Iceland",
        "Guadeloupe",
        "Ethiopia",
        "United States Minor Outlying Islands",
        "Colombia",
        "Nigeria",
        "East Timor",
        "Taiwan",
        "Portugal",
        "Moldova",
        "Guernsey",
        "Madagascar",
        "Ecuador",
        "Senegal",
        "Western Sahara",
        "Maldives",
        "American Samoa",
        "Saint Pierre and Miquelon",
        "Curaçao",
        "France",
        "Lithuania",
        "Rwanda",
        "Zambia",
        "The Gambia",
        "Wallis and Futuna",
        "Jersey",
        "Faroe Islands",
        "Guatemala",
        "Denmark",
        "Isle of Man",
        "Saint Martin",
        "Australia",
        "Austria",
        "Svalbard and Jan Mayen",
        "Venezuela",
        "Palau",
        "Kenya",
        "Turkey",
        "Albania",
        "Oman",
        "Tuvalu",
        "Åland Islands",
        "Brunei",
        "Tunisia",
        "Russia",
        "South Korea",
        "Barbados",
        "Brazil",
        "Ivory Coast",
        "Serbia",
        "Equatorial Guinea",
        "United States",
        "Qatar",
        "Samoa",
        "Azerbaijan",
        "Guinea-Bissau",
        "Swaziland",
        "Tonga",
        "Canada",
        "Ukraine",
        "Republic of Kosovo",
        "Palestine",
        "Anguilla",
        "Central African Republic",
        "Switzerland",
        "Cyprus",
        "Bosnia and Herzegovina",
        "Singapore",
        "South Georgia",
        "Somalia",
        "Uzbekistan",
        "Cameroon",
        "Poland",
        "Kuwait",
        "Eritrea",
        "Gabon",
        "Cayman Islands",
        "United Arab Emirates",
        "Estonia",
        "Malawi",
        "Spain",
        "Iraq",
        "El Salvador",
        "Mali",
        "Republic of Ireland",
        "Iran",
        "Aruba",
        "Sierra Leone",
        "Panama",
        "Sudan",
        "Solomon Islands",
        "New Zealand",
        "Monaco",
        "Italy",
        "Japan",
        "Kyrgyzstan",
        "Uganda",
        "New Caledonia",
        "Papua New Guinea",
        "Argentina",
        "Sweden",
        "The Bahamas",
        "Bahrain",
        "Armenia",
        "Nauru",
        "Cuba"
    )
)
